algorithm_type: "shared"
algorithm_class: "ppo"
framework: "torch"
tune:
   tune: true # if true, tune hyperparameters in main!
   num_samples: 10
   max_episodes: 25000
   max_concurrent_trials: 12
analysis:
   pref_ccm_analysis: true
   pref_granger_analysis: false
   pref_graph_analysis: false
   pref_spatial_ccm_analysis: false
training:
   lr: 0.0001
   use_critic: true
   use_kl_loss: true
   sgd_minibatch_size: 128
   num_sgd_iter: 5
   train_batch_size: 500
   model: 
      conv_filters: [[16, [3, 3], 2]]
      fcnet_hiddens: [256, 256]
      fcnet_activation: "relu"
      conv_activation: "relu"
evaluate:
   eval_episodes: 500
rollouts:
   num_rollout_workers: 0
   batch_mode: "complete_episodes"
wandb: 
   wandb_init: true 
   wandb_project: "rllib1"
   wandb_entity: "tpn"
   wandb_notes: "testing setup"
   wandb_log_freq: 50
env_name: "discrete_pp_v1"
env_config:
   map_size: 15
   pred_vision: 2
   prey_type: "static"
   max_cycles: 100
   npred: 2
   nprey: 6
   reward_type: "type_1"
ray:
   init_dashboard: false