wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1649029672
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 2
      - 17
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
logfile:
  desc: null
  value: logs/log.txt
loglevel:
  desc: null
  value: 20
message:
  desc: null
  value: random
train:
  desc: null
  value: true
