infer:
    global:
        size: 15
        winsize: 9
        npred: 1
        nprey: 1
        
    sce_1:
        npred: 2 
        nprey: 2
        pred_pos: [!!python/tuple [3,3], !!python/tuple [2,5]]
        prey_pos: [!!python/tuple [3,4], !!python/tuple [6,2]]
        target_pred: [!!python/tuple [3,3]]
        plot_file: "0/plot1"
    
    sce_2:
        npred: 2 
        nprey: 2
        pred_pos: []
        prey_pos: []
        target_pos: []
        plot_file: "1/plot1"
